config/routes.rb
Dcards::Application.routes.draw do

  
     resources :customers do
        collection do 
         get 'dashboard'
        end 
     end

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
   layout 'admin_layout'
	
	def index

	end

	def new

	end
    def dashboard
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/dashboard.html.erb
<!-- BEGIN Breadcrumb -->
    <div id="breadcrumbs">
      <ul class="breadcrumb">
        <li> <i class="icon-home"></i><%#=link_to "Home", dashboard_admins_path%> <span class="divider"><i class="icon-angle-right"></i></span> </li>
        <li class="active">Dashboard</li>
      </ul>
    </div>
    <% if flash[:notice]%>
      <div class="success_msg"> 
        <i class="icon-check"></i><span class="text-success"><%= flash[:notice] %></span><br />
      </div>
    <% end %>
   <% if flash[:error]%>
      <div class="success_msg"> 
         <i class="icon-remove"></i><span class="text-error"><%= flash[:error]%></span><br />
      </div>
    <% end %>
    <!-- END Breadcrumb -->
    <!-- BEGIN Main Content -->
    <div class="row">
      <div class="col-md-7">
        <div class="row">
          <div class="col-md-7">
            <div class="row">
              <div class="col-md-6 tile-active"> <a class="tile tile-pink" data-stop="3000" href="#">
                <div class="img img-center"> <img src="img/demo/wp-logo.png" /> </div>
                <p class="title text-center">Visit Siri Innovations</p>
                </a> <a class="tile tile-orange" href="#">
                <p>This is admin area</p>
                </a> </div>
              <div class="col-md-6"> <a class="tile tile-red" href="#">
                <div class="img img-center"> <i class="icon-shopping-cart"></i> </div>
                <p class="title text-center">siri</p>
                </a> </div>
            </div>
          </div>
          <div class="col-md-5">
            <div class="row">
              <div class="col-md-12">
                <div class="tile tile-green">
                  <div class="img"> <i class="icon-copy"></i> </div>
                  <div class="content">
                    <p class="big">+30</p>
                    <p class="title">Ready Page</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-5">
        <div class="row">
          <div class="col-md-6">
            <div class="tile tile-orange">
              <div class="img"> <i class="icon-comments"></i> </div>
              <div class="content">
                <p class="big">128</p>
                <p class="title">Comments</p>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="tile tile-dark-blue">
              <div class="img"> <i class="icon-download-alt"></i> </div>
              <div class="content">
                <p class="big">+160</p>
                <p class="title">Downloads</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    
    <!-- END Tiles --> 
    
    <!-- BEGIN Main Content -->
    <div class="row">
      <div class="col-md-7">
        <div class="box">
          <div class="box-title">
            <h3><i class="icon-bar-chart"></i> Visitors Chart</h3>
            <div class="box-tool"> <a data-action="collapse" href="#"><i class="icon-chevron-up"></i></a> <a data-action="close" href="#"><i class="icon-remove"></i></a> </div>
          </div>
          <div class="box-content">
            <div id="visitors-chart" style="margin-top:20px; position:relative; height: 290px;"></div>
          </div>
        </div>
      </div>
      <div class="col-md-5">
        <div class="box">
          <div class="box-title">
            <h3><i class="icon-bar-chart"></i> Weekly Visitors Stat</h3>
            <div class="box-tool"> <a data-action="collapse" href="#"><i class="icon-chevron-up"></i></a> <a data-action="close" href="#"><i class="icon-remove"></i></a> </div>
          </div>
          <div class="box-content">
            <ul class="weekly-stats">
              <li> <span class="inline-sparkline">134,178,264,196,307,259,287</span> Visits: <span class="value">376</span> </li>
              <li> <span class="inline-sparkline">89,124,197,138,235,169,186</span> Unique Visitors: <span class="value">238</span> </li>
              <li> <span class="inline-sparkline">625,517,586,638,669,698,763</span> Page Views: <span class="value">514</span> </li>
              <li> <span class="inline-sparkline">1.34,2.98,0.76,1.29,1.86,1.68,1.92</span> Pages / Visit: <span class="value">1.43</span> </li>
              <li> <span class="inline-sparkline">2.34,2.67,1.47,1.97,2.25,2.47,1.27</span> Avg. Visit Time: <span class="value">00:02:34</span> </li>
              <li> <span class="inline-sparkline">70.34,67.41,59.45,65.43,78.42,75.92,74.29</span> Bounce Rate: <span class="value">73.56%</span> </li>
              <li> <span class="inline-sparkline">78.12,74.52,81.25,89.23,86.15,91.82,85.18</span> % New Visits: <span class="value">82.65%</span> </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <!-- END Main Content -->
    
    <footer>
      <p>© Siri IT Innovations Pvt Ltd, 2013. All rights reserved.</p>
      <div class="pageload">Page Load Time: <label id="lbltxt" style="font-weight:bold; color:Red"></label>
</div>
    </footer>
    <a id="btn-scrollup" class="btn btn-circle btn-lg" href="#"><i class="icon-chevron-up"></i></a> </div>

app/views/customers/index.html.erb
<h1>hai this is index page </h1>

app/views/layouts/admin_layout.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title>Dashboard - Dcards</title>
<meta name="description" content="">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= csrf_meta_tag %>

<%=favicon_link_tag("favicon.ico")%>

</head>
<body class="skin-black"> 
<!-- BEGIN Navbar -->
<div id="navbar" class="navbar">
  <button type="button" class="navbar-toggle navbar-btn collapsed" data-toggle="collapse" data-target="#sidebar"> <span class="icon-reorder"></span> </button>
  <div class="col-sm-3 col-lg-3 controls">  
   <small> <%= link_to (image_tag 'logo-large.png') %></small> 
   
  </div>
  
  <!-- BEGIN Navbar Buttons -->
  <ul class="nav flaty-nav pull-right">
    
    <!-- BEGIN Site Credits -->
    <li class="hidden-xs"> <a data-toggle="dropdown" class="dropdown-toggle siri" href="#">
     <%= image_tag("siri.png",:alt => "Siri Innovations",:title => "siriinnovations") %>
    </a>
      <!-- BEGIN Tasks Dropdown -->
      <ul class="dropdown-navbar dropdown-menu hover">
        <li class="nav-header"> <i class="glyphicon glyphicon-user"></i>Developers</li>
        <li class="siri-in">
          <div class="siri-inner">
            <div class="logo-align"> 
            <%= image_tag("siri-logo.png",:alt => "Siri Innovations",:title => "siriinnovations") %>
           </div>
          </div>
        </li>
        <li class="more"><a href="http://www.siriinnovations.com" target="_blank">www.siriinnovations.com</a> </li>
      </ul>
      <!-- END Tasks Dropdown --> 
    </li>
    <!-- END Site Credits -->
    <!-- BEGIN Button Tasks -->
    <li class="hidden-xs"> <a data-toggle="dropdown" class="dropdown-toggle" href="#"> <i class="icon-tasks"></i> <span class="badge badge-success"></span> </a> 
              
              <!-- BEGIN Tasks Dropdown -->
              <ul class="dropdown-navbar dropdown-menu">
                <li class="nav-header"> <i class="icon-ok"></i>Newly Registred Users</li>
                <li> <a href="#">
                     <div class="clearfix">
                       <span class="pull-left"></span><span class="pull-right"></span>   
                     </div>            
                    </a> </li>
      </ul>
      <!-- END Tasks Dropdown --> 
    </li>
    
    <li class="user-profile"> <a data-toggle="dropdown" 
    href="#" class="user-menu dropdown-toggle"> <img class="nav-user-photo" 
    <%= image_tag('avatar2.jpg')%> <span id="user_info">User</span> 
    <i class="icon-caret-down"></i> </a> 
      
      <!-- BEGIN User Dropdown -->
      <ul class="dropdown-menu dropdown-navbar" id="user_menu">
        <li class="nav-header"><i class="icon-time"></i> Logged In At <%#= current_admin.current_sign_in_at.localtime.strftime('%H:%M:%S') %> </li>
        <li><%=link_to "<i class='icon-user'></i>View Profile".html_safe%></li>
        
        <li class="divider visible-xs"></li>
        <li class="visible-xs logo-align"> 
          <a href="http://www.siriinnovations.com/" target="_blank"> <%#= image_tag("siri.png",:alt => "Siri Innovations",:title => "siriinnovations") %> 
        </li>
        
        <li> 
         <%=link_to "<i class='icon-off'></i>Logout".html_safe%>
         </li>
      </ul>
      <!-- BEGIN User Dropdown --> 
    </li>
    <!-- END Button User -->
  </ul>
  <!-- END Navbar Buttons --> 
</div>
<!-- END Navbar --> 

<!-- BEGIN Container -->
<div class="container" id="main-container"> 
  <!-- BEGIN Sidebar -->
  <div id="sidebar" class="navbar-collapse collapse"> 
    <!-- BEGIN Navlist -->
    <ul class="nav nav-list">
      <li><%=link_to "<i class='icon-dashboard'></i>Dashboard".html_safe,dashboard_customers_path %></li>
      <li><%=link_to "<i class='icon-book'></i>Coustomers".html_safe %></li>
      <li><%=link_to "<i class='icon-list'></i>Merchants".html_safe %></li>
      <li><%=link_to "<i class='icon-user'></i>Users".html_safe %></li> 
      
      <%# if current_admin.role %>
      <li><%=link_to "<i class='glyphicon glyphicon-import'></i>Admin Users".html_safe  %></li> 
       <li><%=link_to "<i class='icon-table'></i>Activities".html_safe %></li> 
      <li><%=link_to "<i class='icon-user'></i>Admin Users".html_safe %></li> 
      <%# end %>
      
      <li> <a href="#" class="dropdown-toggle"><i class="glyphicon glyphicon-facetime-video"></i><span>Video management</span> <b class="arrow icon-angle-right"></b> </a>       
        <!-- BEGIN Submenu -->
        <ul class="submenu">
         
          <li><%= link_to "Videos Manager"%></li>
        
          <li><%= link_to "Trailer Video Settings"%></li>
          
        </ul>
        <!-- END Submenu -->
      </li>
    </ul>
    <!-- END Navlist --> 
    
    <!-- BEGIN Sidebar Collapse Button -->
    <div id="sidebar-collapse" class="visible-lg"> <i class="icon-double-angle-left"></i> </div>
    <!-- END Sidebar Collapse Button --> 
  </div>
  <!-- END Sidebar --> 
  
  <!-- BEGIN Content -->
  <div id="main-content"> 
    <!-- BEGIN Main Content -->
     <%= yield %>
      <!-- END Main Content -->
    <a id="btn-scrollup" class="btn btn-circle btn-lg" href="#"><i class="icon-chevron-up"></i></a> 
  </div>
  <!-- END Content --> 
</div>
<!-- END Container --> 
<!--basic scripts--> 
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dcards</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>